spring:
  security:
    oauth2:
      client:
        registration:
          google:
            client-id: 229666542925-10vg43mj7b66bp06vkakne3spsr309pp.apps.googleusercontent.com
            client-secret: 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
            scope:
              - email
              - profile
          twitter:
            clientId: OHZuVXNLOU9Yd2xEZTM1Q3pSTl86MTpjaQ
            clientSecret: dkHPKnXel9A99r2NU1SkHDF56Up-hWemOVe_aPmcjhSXxxyiKn
#            client-id: OHZuVXNLOU9Yd2xEZTM1Q3pSTl86MTpjaQ
#            client-secret: dkHPKnXel9A99r2NU1SkHDF56Up-hWemOVe_aPmcjhSXxxyiKn
#            scope: tweet.read,users.read
            scope:
#              - profile
              - tweet.read
              - tweet.write
#              - offline.access
#              - users.read
#            code_challenge: challenge
#            code_challenge_method: plain
            client-name: Twitter
            authorization-grant-type: authorization_code
#            redirect-uri: https://example.com/login/oauth2/code/twitter
            redirect-uri: http://localhost:8080/lo
            client-authentication-method: none
          naver:
            client-id: j47oXSCn9p1bun_cJTP3
            client-secret: uZjcqLYEPv
            scope:
              - name
              - email
            client-name: Naver
            authorization-grant-type: authorization_code
            redirect-uri: http://localhost:8080/login/oauth2/code/naver

        provider:
          naver:
            authorization-uri: https://nid.naver.com/oauth2.0/authorize
            token-uri: https://nid.naver.com/oauth2.0/token
            use-info-uri: https://openapi.naver.com/v1/nid/me
            user-name-attribute: response
          twitter:
#            authorization-uri: https://twitter.com/i/oauth2/authorize?code_challenge=challenge&code_challenge_method=plain&
            authorization-uri: https://twitter.com/i/oauth2/authorize
            token-uri: https://api.twitter.com/2/oauth2/token
            use-info-uri: https://api.twitter.com/2/users/me
            user-name-attribute: response
